package org.snu.cse.cap.translator.structure.channel;

public enum CommunicationType {
	SHARED_MEMORY,
	TCP_CLIENT_READER,
	TCP_SERVER_WRITER,
	TCP_CLIENT_WRITER,
	TCP_SERVER_READER,
	BLUETOOTH_MASTER_READER,
	BLUETOOTH_MASTER_WRITER,
	BLUETOOTH_SLAVE_READER,
	BLUETOOTH_SLAVE_WRITER,
	SERIAL_MASTER_READER,
	SERIAL_MASTER_WRITER,
	SERIAL_SLAVE_READER,
	SERIAL_SLAVE_WRITER,
}