#ifndef __CIC_CONMAP_H__
#define __CIC_CONMAP_H__

CIC_TYPEDEF CIC_T_ENUM {SHARED_CONN, WIFI_CONN, BLUETOOTH_CONN, RF_CONN, I2C_CONN, SERIAL_CONN, UART_CONN, USB_CONN} CIC_UT_CONN_TYPE;
CIC_TYPEDEF CIC_T_ENUM {CON_NOR_CHANNEL, CON_LIB_CHANNEL} CIC_UT_CON_CHANNEL_TYPE;

CIC_TYPEDEF CIC_T_STRUCT
{
    CIC_UT_CON_CHANNEL_TYPE lib_or_ch;
    CIC_T_INT channel_id;
    CIC_UT_CONN_TYPE conn_type;
} CIC_UT_CONNECTIONMAP;

#endif /* __CIC_CONMAP_H__ */