#ifndef __CIC_CONTROL_H__
#define __CIC_CONTROL_H__

#define MAX_TIME_BASE_COUNT 10
#define MAX_TIMER_SLOT_SIZE 10
#define SEND_PACKET_SIZE 15
#define CONTROL_JOB_Q_SIZE 100
#define RCV_BUF_SIZE 20

CIC_TYPEDEF CIC_T_ENUM {
	DATA_PACKET,
	CONTROL_PACKET,
} CIC_UT_PACKET_TYPE;

CIC_TYPEDEF CIC_T_ENUM {
	RUN_TASK,
	STOP_TASK,
	SUSPEND_TASK,
	RESUME_TASK,
	PROGRAM_STOP,
	GET_PARAM_INT,
	SET_PARAM_INT,
	GET_PARAM_FLOAT,
	SET_PARAM_FLOAT,
	BEGIN,
	END,
	GET_TIME_NOW,
	TIME_RESPONSE,
} CIC_UT_COMMAND_TYPE;

CIC_TYPEDEF CIC_T_STRUCT {
	CIC_T_UINT task_id;
	CIC_T_UINT param_id;
	CIC_T_CHAR *task_name;
	CIC_T_CHAR *param_name;
	CIC_T_VOID *param_value;
} CIC_UT_PARAM;

CIC_TYPEDEF CIC_T_STRUCT {
	CIC_T_UINT control_task_id;
	CIC_T_UINT control_priority;
	CIC_T_UINT control_group_id;
	CIC_T_INT empty_slot_index;
	CIC_T_INT empty_base_index;
	CIC_T_UINT time_base[MAX_TIME_BASE_COUNT];
	CIC_T_UINT timer_slot[MAX_TIMER_SLOT_SIZE];
} CIC_UT_CONTROL_CHANNEL;

#endif /* __CIC_CONTROL_H__ */
