#ifndef __CIC_TASKS_H__
#define __CIC_TASKS_H__

#define TASK_PREINIT 	(*tasks[task_index].PreInit)()
#define TASK_INIT 		(*tasks[task_index].Init)(task_index)
#define TASK_PREGO 		(*tasks[task_index].PreGo)()
#define TASK_GO 		(*tasks[task_index].Go)()
#define TASK_POSTGO 	(*tasks[task_index].PostGo)()
#define TASK_WRAPUP 	(*tasks[task_index].Wrapup)()
#define TASK_POSTWRAPUP (*tasks[task_index].PostWrapup)()

CIC_TYPEDEF CIC_T_VOID (*CIC_UT_PREINIT_FUNC)(CIC_T_VOID);
CIC_TYPEDEF CIC_T_VOID (*CIC_UT_INIT_FUNC)(CIC_T_INT);
CIC_TYPEDEF CIC_T_VOID (*CIC_UT_PREGO_FUNC)(CIC_T_VOID);
CIC_TYPEDEF CIC_T_VOID (*CIC_UT_GO_FUNC)(CIC_T_VOID);
CIC_TYPEDEF CIC_T_VOID (*CIC_UT_POSTGO_FUNC)(CIC_T_VOID);
CIC_TYPEDEF CIC_T_VOID (*CIC_UT_WRAPUP_FUNC)(CIC_T_VOID);
CIC_TYPEDEF CIC_T_VOID (*CIC_UT_POSTWRAPUP_FUNC)(CIC_T_VOID);

CIC_TYPEDEF CIC_T_VOID 	(*CIC_UT_MTM_INITIALIZE_FUNC)();
CIC_TYPEDEF CIC_T_CHAR* (*CIC_UT_GET_CURRENT_MODE_NAME_FUNC)();
CIC_TYPEDEF CIC_T_INT   (*CIC_UT_GET_VAR_INT_FUNC)(CIC_T_CHAR*);
CIC_TYPEDEF CIC_T_VOID  (*CIC_UT_SET_VAR_INT_FUNC)(CIC_T_CHAR*, CIC_T_INT);
CIC_TYPEDEF CIC_T_CHAR* (*CIC_UT_GET_VAR_STRING_FUNC)(CIC_T_CHAR*);
CIC_TYPEDEF CIC_T_VOID  (*CIC_UT_SET_VAR_STRING_FUNC)(CIC_T_CHAR*, CIC_T_CHAR*);
CIC_TYPEDEF CIC_T_BOOL  (*CIC_UT_TRANSITION_FUNC)(CIC_T_VOID);
CIC_TYPEDEF CIC_T_VOID  (*CIC_UT_UPDATE_CURRENT_MODE_FUNC)(CIC_T_CHAR*);
CIC_TYPEDEF CIC_T_INT   (*CIC_UT_GET_TASK_ITER_COUNT_FUNC)(CIC_T_CHAR*);
CIC_TYPEDEF CIC_T_INT   (*CIC_UT_GET_TASK_REPEAT_COUNT_FUNC)(CIC_T_CHAR*, CIC_T_INT);

CIC_TYPEDEF CIC_T_ENUM {COMPUTATIONAL, CONTROL, VIRTUAL} CIC_UT_TASK_TYPE;
CIC_TYPEDEF CIC_T_ENUM {DATA_DRIVEN, TIME_DRIVEN, CONTROL_DRIVEN} CIC_UT_TASK_DRIVEN_TYPE;
CIC_TYPEDEF CIC_T_ENUM {STATE_RUN, STATE_STOP, STATE_WAIT, STATE_END} CIC_UT_TASK_STATE;
CIC_TYPEDEF CIC_T_ENUM {RUNNING, READ_BLOCK, WRITE_BLOCK, NONE} CIC_UT_TASK_RUN_STATE;
CIC_TYPEDEF CIC_T_ENUM {H, M, S, MS, US, NS, PS, FS, CYCLE, COUNT} CIC_UT_PERIOD_MATRIC;

CIC_TYPEDEF CIC_T_STRUCT {
    CIC_T_INT task_id;
    CIC_T_CHAR *name;
    CIC_UT_TASK_TYPE task_type;

	CIC_UT_PREINIT_FUNC PreInit;
    CIC_UT_INIT_FUNC Init;
    
    CIC_UT_PREGO_FUNC PreGo;
    CIC_UT_GO_FUNC Go;
    CIC_UT_POSTGO_FUNC PostGo;
    
    CIC_UT_WRAPUP_FUNC Wrapup;
    CIC_UT_POSTWRAPUP_FUNC PostWrapup;

    CIC_UT_TASK_DRIVEN_TYPE driven_type;
    CIC_UT_TASK_STATE state;
    CIC_UT_TASK_RUN_STATE run_state;
    CIC_UT_PERIOD_MATRIC p_metric;

    CIC_T_UINT run_rate;
    CIC_T_UINT period;
    CIC_T_UINT global_period;
    CIC_T_UINT run_count;

    CIC_T_BOOL has_mtm;
    CIC_T_BOOL has_subgraph;

	CIC_T_BOOL is_src_task;
    CIC_T_BOOL is_child_task;
    CIC_T_INT parent_task_id;

    CIC_T_MUTEX mutex;
    CIC_T_COND cond;

    CIC_T_THREAD thread;
} CIC_UT_TASK;

CIC_TYPEDEF CIC_T_STRUCT{
    CIC_T_INT task_id;
    CIC_T_BOOL is_sdf;
    CIC_UT_MTM_INITIALIZE_FUNC Initialize;
    CIC_UT_GET_CURRENT_MODE_NAME_FUNC GetCurrentModeName;
    CIC_UT_SET_VAR_INT_FUNC SetVariableInt;
    CIC_UT_GET_VAR_INT_FUNC GetVariableInt;
    CIC_UT_SET_VAR_STRING_FUNC SetVariableString;
    CIC_UT_GET_VAR_STRING_FUNC GetVariableString;
    CIC_UT_TRANSITION_FUNC Transition;
    CIC_UT_UPDATE_CURRENT_MODE_FUNC UpdateCurrentMode;
    CIC_UT_GET_TASK_ITER_COUNT_FUNC GetTaskIterCount;
    CIC_UT_GET_TASK_REPEAT_COUNT_FUNC GetTaskRepeatCount;
    CIC_T_MUTEX mutex;
    CIC_T_COND cond;
    CIC_T_BARRIER barrier;
} CIC_UT_MTM;

#endif /* __CIC_TASKS_H__ */
