//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.29 at 01:56:08 PM KST 
//


package hopes.cic.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LibraryConnectionListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LibraryConnectionListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="taskLibraryConnection" type="{http://peace.snu.ac.kr/CICXMLSchema}TaskLibraryConnectionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="libraryLibraryConnection" type="{http://peace.snu.ac.kr/CICXMLSchema}LibraryLibraryConnectionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LibraryConnectionListType", propOrder = {
    "taskLibraryConnection",
    "libraryLibraryConnection"
})
public class LibraryConnectionListType {

    protected List<TaskLibraryConnectionType> taskLibraryConnection;
    protected List<LibraryLibraryConnectionType> libraryLibraryConnection;

    /**
     * Gets the value of the taskLibraryConnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taskLibraryConnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaskLibraryConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaskLibraryConnectionType }
     * 
     * 
     */
    public List<TaskLibraryConnectionType> getTaskLibraryConnection() {
        if (taskLibraryConnection == null) {
            taskLibraryConnection = new ArrayList<TaskLibraryConnectionType>();
        }
        return this.taskLibraryConnection;
    }

    /**
     * Gets the value of the libraryLibraryConnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the libraryLibraryConnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLibraryLibraryConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LibraryLibraryConnectionType }
     * 
     * 
     */
    public List<LibraryLibraryConnectionType> getLibraryLibraryConnection() {
        if (libraryLibraryConnection == null) {
            libraryLibraryConnection = new ArrayList<LibraryLibraryConnectionType>();
        }
        return this.libraryLibraryConnection;
    }

}
